
source 'https://github.com/CocoaPods/Specs'

use_frameworks!

platform :ios, '11.0'

target 'TLCore_Example' do
#  use_frameworks!
  pod 'TLCore', :path => '../'
  
#  pod 'gRPC', '1.49.0'
#  pod 'Protobuf', '3.22.0'
#  pod 'gRPC-Core', '1.49.0'
#  pod 'gRPC-ProtoRPC', '1.49.0'
#  pod 'gRPC-RxLibrary', '1.49.0'
#  pod '!ProtoCompiler', '3.21.5'
#  pod '!ProtoCompiler-gRPCPlugin', '1.49.0'
  
#  pod 'TrustKeystore', :git => 'https://github.com/TRON-US/TrustKeystore', :branch => 'TrustKeystore_0.4.0'
#  pod 'TrustCore', :git => 'https://github.com/TRON-US/TrustCore', :branch => 'TrustCore_0.0.7'
#  pod 'TrezorCrypto', :git => 'https://github.com/TRON-US/trezor-crypto-ios', inhibit_warnings: true
#  pod 'CryptoSwift', :git => 'https://github.com/TRON-US/CryptoSwift', :branch => 'stack'
#  pod 'web3swift.pod', :git => 'https://github.com/TRON-US/web3swift', :branch => 'master'

  target 'TLCore_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
#        if ['gRPC-gRPCCertificates'].include? target.name
#            target.build_configurations.each do |config|
#                fix_config(config)
#            end
#        end
        if ['TrustKeystore'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
            end
        end
        
        if ['TrustCore'].include? target.name
          target.build_configurations.each do |config|
            config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
          end
        end
    end

    installer.aggregate_targets.each do |target|
        target.xcconfigs.each do |variant, xcconfig|
          xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
          IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
        end
    end
      
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
          xcconfig_path = config.base_configuration_reference.real_path
          IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
        end
      end
    end
    
#    installer.pods_project.build_configurations.each do |config|
#      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#    end
end

