// Generated by the protocol buffer compiler.  DO NOT EDIT!
// clang-format off
// source: core/contract/account_contract.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
#define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
#import <Protobuf/GPBProtocolBuffers.h>
#else
#import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Permission;
GPB_ENUM_FWD_DECLARE(AccountType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AccountContractRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface AccountContractRoot : GPBRootObject
@end

#pragma mark - AccountCreateContract

typedef GPB_ENUM(AccountCreateContract_FieldNumber) {
    AccountCreateContract_FieldNumber_OwnerAddress = 1,
    AccountCreateContract_FieldNumber_AccountAddress = 2,
    AccountCreateContract_FieldNumber_Type = 3,
};

GPB_FINAL @interface AccountCreateContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSData *accountAddress;

@property(nonatomic, readwrite) enum AccountType type;

@end

/**
 * Fetches the raw value of a @c AccountCreateContract's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AccountCreateContract_Type_RawValue(AccountCreateContract *message);
/**
 * Sets the raw value of an @c AccountCreateContract's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAccountCreateContract_Type_RawValue(AccountCreateContract *message, int32_t value);

#pragma mark - AccountUpdateContract

typedef GPB_ENUM(AccountUpdateContract_FieldNumber) {
    AccountUpdateContract_FieldNumber_AccountName = 1,
    AccountUpdateContract_FieldNumber_OwnerAddress = 2,
};

/**
 * Update account name. Account name is not unique now.
 **/
GPB_FINAL @interface AccountUpdateContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *accountName;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@end

#pragma mark - SetAccountIdContract

typedef GPB_ENUM(SetAccountIdContract_FieldNumber) {
    SetAccountIdContract_FieldNumber_AccountId = 1,
    SetAccountIdContract_FieldNumber_OwnerAddress = 2,
};

/**
 * Set account id if the account has no id. Account id is unique and case insensitive.
 **/
GPB_FINAL @interface SetAccountIdContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *accountId;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@end

#pragma mark - AccountPermissionUpdateContract

typedef GPB_ENUM(AccountPermissionUpdateContract_FieldNumber) {
    AccountPermissionUpdateContract_FieldNumber_OwnerAddress = 1,
    AccountPermissionUpdateContract_FieldNumber_Owner = 2,
    AccountPermissionUpdateContract_FieldNumber_Witness = 3,
    AccountPermissionUpdateContract_FieldNumber_ActivesArray = 4,
};

GPB_FINAL @interface AccountPermissionUpdateContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

/** Empty is invalidate */
@property(nonatomic, readwrite, strong, null_resettable) Permission *owner;
/** Test to see if @c owner has been set. */
@property(nonatomic, readwrite) BOOL hasOwner;

/** Can be empty */
@property(nonatomic, readwrite, strong, null_resettable) Permission *witness;
/** Test to see if @c witness has been set. */
@property(nonatomic, readwrite) BOOL hasWitness;

/** Empty is invalidate */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Permission*> *activesArray;
/** The number of items in @c activesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger activesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
