// Generated by the protocol buffer compiler.  DO NOT EDIT!
// clang-format off
// source: core/contract/balance_contract.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
#define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
#import <Protobuf/GPBProtocolBuffers.h>
#else
#import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AccountIdentifier;
@class BlockBalanceTrace_BlockIdentifier;
@class TransactionBalanceTrace;
@class TransactionBalanceTrace_Operation;
GPB_ENUM_FWD_DECLARE(ResourceCode);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - BalanceContractRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface BalanceContractRoot : GPBRootObject
@end

#pragma mark - FreezeBalanceContract

typedef GPB_ENUM(FreezeBalanceContract_FieldNumber) {
    FreezeBalanceContract_FieldNumber_OwnerAddress = 1,
    FreezeBalanceContract_FieldNumber_FrozenBalance = 2,
    FreezeBalanceContract_FieldNumber_FrozenDuration = 3,
    FreezeBalanceContract_FieldNumber_Resource = 10,
    FreezeBalanceContract_FieldNumber_ReceiverAddress = 15,
};

GPB_FINAL @interface FreezeBalanceContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite) int64_t frozenBalance;

@property(nonatomic, readwrite) int64_t frozenDuration;

@property(nonatomic, readwrite) enum ResourceCode resource;

@property(nonatomic, readwrite, copy, null_resettable) NSData *receiverAddress;

@end

/**
 * Fetches the raw value of a @c FreezeBalanceContract's @c resource property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t FreezeBalanceContract_Resource_RawValue(FreezeBalanceContract *message);
/**
 * Sets the raw value of an @c FreezeBalanceContract's @c resource property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetFreezeBalanceContract_Resource_RawValue(FreezeBalanceContract *message, int32_t value);

#pragma mark - UnfreezeBalanceContract

typedef GPB_ENUM(UnfreezeBalanceContract_FieldNumber) {
    UnfreezeBalanceContract_FieldNumber_OwnerAddress = 1,
    UnfreezeBalanceContract_FieldNumber_Resource = 10,
    UnfreezeBalanceContract_FieldNumber_ReceiverAddress = 15,
};

GPB_FINAL @interface UnfreezeBalanceContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite) enum ResourceCode resource;

@property(nonatomic, readwrite, copy, null_resettable) NSData *receiverAddress;

@end

/**
 * Fetches the raw value of a @c UnfreezeBalanceContract's @c resource property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t UnfreezeBalanceContract_Resource_RawValue(UnfreezeBalanceContract *message);
/**
 * Sets the raw value of an @c UnfreezeBalanceContract's @c resource property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetUnfreezeBalanceContract_Resource_RawValue(UnfreezeBalanceContract *message, int32_t value);

#pragma mark - WithdrawBalanceContract

typedef GPB_ENUM(WithdrawBalanceContract_FieldNumber) {
    WithdrawBalanceContract_FieldNumber_OwnerAddress = 1,
};

GPB_FINAL @interface WithdrawBalanceContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@end

#pragma mark - TransferContract

typedef GPB_ENUM(TransferContract_FieldNumber) {
    TransferContract_FieldNumber_OwnerAddress = 1,
    TransferContract_FieldNumber_ToAddress = 2,
    TransferContract_FieldNumber_Amount = 3,
};

GPB_FINAL @interface TransferContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSData *toAddress;

@property(nonatomic, readwrite) int64_t amount;

@end

#pragma mark - TransactionBalanceTrace

typedef GPB_ENUM(TransactionBalanceTrace_FieldNumber) {
    TransactionBalanceTrace_FieldNumber_TransactionIdentifier = 1,
    TransactionBalanceTrace_FieldNumber_OperationArray = 2,
    TransactionBalanceTrace_FieldNumber_Type = 3,
    TransactionBalanceTrace_FieldNumber_Status = 4,
};

GPB_FINAL @interface TransactionBalanceTrace : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *transactionIdentifier;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TransactionBalanceTrace_Operation*> *operationArray;
/** The number of items in @c operationArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger operationArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *status;

@end

#pragma mark - TransactionBalanceTrace_Operation

typedef GPB_ENUM(TransactionBalanceTrace_Operation_FieldNumber) {
    TransactionBalanceTrace_Operation_FieldNumber_OperationIdentifier = 1,
    TransactionBalanceTrace_Operation_FieldNumber_Address = 2,
    TransactionBalanceTrace_Operation_FieldNumber_Amount = 3,
};

GPB_FINAL @interface TransactionBalanceTrace_Operation : GPBMessage

@property(nonatomic, readwrite) int64_t operationIdentifier;

@property(nonatomic, readwrite, copy, null_resettable) NSData *address;

@property(nonatomic, readwrite) int64_t amount;

@end

#pragma mark - BlockBalanceTrace

typedef GPB_ENUM(BlockBalanceTrace_FieldNumber) {
    BlockBalanceTrace_FieldNumber_BlockIdentifier = 1,
    BlockBalanceTrace_FieldNumber_Timestamp = 2,
    BlockBalanceTrace_FieldNumber_TransactionBalanceTraceArray = 3,
};

GPB_FINAL @interface BlockBalanceTrace : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BlockBalanceTrace_BlockIdentifier *blockIdentifier;
/** Test to see if @c blockIdentifier has been set. */
@property(nonatomic, readwrite) BOOL hasBlockIdentifier;

@property(nonatomic, readwrite) int64_t timestamp;

/**  BlockIdentifier parent_block_identifier = 4; */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TransactionBalanceTrace*> *transactionBalanceTraceArray;
/** The number of items in @c transactionBalanceTraceArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger transactionBalanceTraceArray_Count;

@end

#pragma mark - BlockBalanceTrace_BlockIdentifier

typedef GPB_ENUM(BlockBalanceTrace_BlockIdentifier_FieldNumber) {
    BlockBalanceTrace_BlockIdentifier_FieldNumber_Hash_p = 1,
    BlockBalanceTrace_BlockIdentifier_FieldNumber_Number = 2,
};

GPB_FINAL @interface BlockBalanceTrace_BlockIdentifier : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *hash_p;

@property(nonatomic, readwrite) int64_t number;

@end

#pragma mark - AccountTrace

typedef GPB_ENUM(AccountTrace_FieldNumber) {
    AccountTrace_FieldNumber_Balance = 1,
    AccountTrace_FieldNumber_Placeholder = 99,
};

GPB_FINAL @interface AccountTrace : GPBMessage

@property(nonatomic, readwrite) int64_t balance;

@property(nonatomic, readwrite) int64_t placeholder;

@end

#pragma mark - AccountIdentifier

typedef GPB_ENUM(AccountIdentifier_FieldNumber) {
    AccountIdentifier_FieldNumber_Address = 1,
};

GPB_FINAL @interface AccountIdentifier : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *address;

@end

#pragma mark - AccountBalanceRequest

typedef GPB_ENUM(AccountBalanceRequest_FieldNumber) {
    AccountBalanceRequest_FieldNumber_AccountIdentifier = 1,
    AccountBalanceRequest_FieldNumber_BlockIdentifier = 2,
};

GPB_FINAL @interface AccountBalanceRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) AccountIdentifier *accountIdentifier;
/** Test to see if @c accountIdentifier has been set. */
@property(nonatomic, readwrite) BOOL hasAccountIdentifier;

@property(nonatomic, readwrite, strong, null_resettable) BlockBalanceTrace_BlockIdentifier *blockIdentifier;
/** Test to see if @c blockIdentifier has been set. */
@property(nonatomic, readwrite) BOOL hasBlockIdentifier;

@end

#pragma mark - AccountBalanceResponse

typedef GPB_ENUM(AccountBalanceResponse_FieldNumber) {
    AccountBalanceResponse_FieldNumber_Balance = 1,
    AccountBalanceResponse_FieldNumber_BlockIdentifier = 2,
};

GPB_FINAL @interface AccountBalanceResponse : GPBMessage

@property(nonatomic, readwrite) int64_t balance;

@property(nonatomic, readwrite, strong, null_resettable) BlockBalanceTrace_BlockIdentifier *blockIdentifier;
/** Test to see if @c blockIdentifier has been set. */
@property(nonatomic, readwrite) BOOL hasBlockIdentifier;

@end

#pragma mark - FreezeBalanceV2Contract

typedef GPB_ENUM(FreezeBalanceV2Contract_FieldNumber) {
    FreezeBalanceV2Contract_FieldNumber_OwnerAddress = 1,
    FreezeBalanceV2Contract_FieldNumber_FrozenBalance = 2,
    FreezeBalanceV2Contract_FieldNumber_Resource = 3,
};

GPB_FINAL @interface FreezeBalanceV2Contract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite) int64_t frozenBalance;

@property(nonatomic, readwrite) enum ResourceCode resource;

@end

/**
 * Fetches the raw value of a @c FreezeBalanceV2Contract's @c resource property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t FreezeBalanceV2Contract_Resource_RawValue(FreezeBalanceV2Contract *message);
/**
 * Sets the raw value of an @c FreezeBalanceV2Contract's @c resource property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetFreezeBalanceV2Contract_Resource_RawValue(FreezeBalanceV2Contract *message, int32_t value);

#pragma mark - UnfreezeBalanceV2Contract

typedef GPB_ENUM(UnfreezeBalanceV2Contract_FieldNumber) {
    UnfreezeBalanceV2Contract_FieldNumber_OwnerAddress = 1,
    UnfreezeBalanceV2Contract_FieldNumber_UnfreezeBalance = 2,
    UnfreezeBalanceV2Contract_FieldNumber_Resource = 3,
};

GPB_FINAL @interface UnfreezeBalanceV2Contract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite) int64_t unfreezeBalance;

@property(nonatomic, readwrite) enum ResourceCode resource;

@end

/**
 * Fetches the raw value of a @c UnfreezeBalanceV2Contract's @c resource property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t UnfreezeBalanceV2Contract_Resource_RawValue(UnfreezeBalanceV2Contract *message);
/**
 * Sets the raw value of an @c UnfreezeBalanceV2Contract's @c resource property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetUnfreezeBalanceV2Contract_Resource_RawValue(UnfreezeBalanceV2Contract *message, int32_t value);

#pragma mark - WithdrawExpireUnfreezeContract

typedef GPB_ENUM(WithdrawExpireUnfreezeContract_FieldNumber) {
    WithdrawExpireUnfreezeContract_FieldNumber_OwnerAddress = 1,
};

GPB_FINAL @interface WithdrawExpireUnfreezeContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@end

#pragma mark - DelegateResourceContract

typedef GPB_ENUM(DelegateResourceContract_FieldNumber) {
    DelegateResourceContract_FieldNumber_OwnerAddress = 1,
    DelegateResourceContract_FieldNumber_Resource = 2,
    DelegateResourceContract_FieldNumber_Balance = 3,
    DelegateResourceContract_FieldNumber_ReceiverAddress = 4,
    DelegateResourceContract_FieldNumber_Lock = 5,
    DelegateResourceContract_FieldNumber_LockPeriod = 6,
};

GPB_FINAL @interface DelegateResourceContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite) enum ResourceCode resource;

@property(nonatomic, readwrite) int64_t balance;

@property(nonatomic, readwrite, copy, null_resettable) NSData *receiverAddress;

@property(nonatomic, readwrite) BOOL lock;

@property(nonatomic, readwrite) int64_t lockPeriod;

@end

/**
 * Fetches the raw value of a @c DelegateResourceContract's @c resource property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t DelegateResourceContract_Resource_RawValue(DelegateResourceContract *message);
/**
 * Sets the raw value of an @c DelegateResourceContract's @c resource property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetDelegateResourceContract_Resource_RawValue(DelegateResourceContract *message, int32_t value);

#pragma mark - UnDelegateResourceContract

typedef GPB_ENUM(UnDelegateResourceContract_FieldNumber) {
    UnDelegateResourceContract_FieldNumber_OwnerAddress = 1,
    UnDelegateResourceContract_FieldNumber_Resource = 2,
    UnDelegateResourceContract_FieldNumber_Balance = 3,
    UnDelegateResourceContract_FieldNumber_ReceiverAddress = 4,
};

GPB_FINAL @interface UnDelegateResourceContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite) enum ResourceCode resource;

@property(nonatomic, readwrite) int64_t balance;

@property(nonatomic, readwrite, copy, null_resettable) NSData *receiverAddress;

@end

/**
 * Fetches the raw value of a @c UnDelegateResourceContract's @c resource property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t UnDelegateResourceContract_Resource_RawValue(UnDelegateResourceContract *message);
/**
 * Sets the raw value of an @c UnDelegateResourceContract's @c resource property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetUnDelegateResourceContract_Resource_RawValue(UnDelegateResourceContract *message, int32_t value);

#pragma mark - CancelAllUnfreezeV2Contract

typedef GPB_ENUM(CancelAllUnfreezeV2Contract_FieldNumber) {
    CancelAllUnfreezeV2Contract_FieldNumber_OwnerAddress = 1,
};

GPB_FINAL @interface CancelAllUnfreezeV2Contract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
