// Generated by the protocol buffer compiler.  DO NOT EDIT!
// clang-format off
// source: core/contract/exchange_contract.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
#define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
#import <Protobuf/GPBProtocolBuffers.h>
#else
#import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ExchangeContractRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ExchangeContractRoot : GPBRootObject
@end

#pragma mark - ExchangeCreateContract

typedef GPB_ENUM(ExchangeCreateContract_FieldNumber) {
    ExchangeCreateContract_FieldNumber_OwnerAddress = 1,
    ExchangeCreateContract_FieldNumber_FirstTokenId = 2,
    ExchangeCreateContract_FieldNumber_FirstTokenBalance = 3,
    ExchangeCreateContract_FieldNumber_SecondTokenId = 4,
    ExchangeCreateContract_FieldNumber_SecondTokenBalance = 5,
};

GPB_FINAL @interface ExchangeCreateContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSData *firstTokenId;

@property(nonatomic, readwrite) int64_t firstTokenBalance;

@property(nonatomic, readwrite, copy, null_resettable) NSData *secondTokenId;

@property(nonatomic, readwrite) int64_t secondTokenBalance;

@end

#pragma mark - ExchangeInjectContract

typedef GPB_ENUM(ExchangeInjectContract_FieldNumber) {
    ExchangeInjectContract_FieldNumber_OwnerAddress = 1,
    ExchangeInjectContract_FieldNumber_ExchangeId = 2,
    ExchangeInjectContract_FieldNumber_TokenId = 3,
    ExchangeInjectContract_FieldNumber_Quant = 4,
};

GPB_FINAL @interface ExchangeInjectContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite) int64_t exchangeId;

@property(nonatomic, readwrite, copy, null_resettable) NSData *tokenId;

@property(nonatomic, readwrite) int64_t quant;

@end

#pragma mark - ExchangeWithdrawContract

typedef GPB_ENUM(ExchangeWithdrawContract_FieldNumber) {
    ExchangeWithdrawContract_FieldNumber_OwnerAddress = 1,
    ExchangeWithdrawContract_FieldNumber_ExchangeId = 2,
    ExchangeWithdrawContract_FieldNumber_TokenId = 3,
    ExchangeWithdrawContract_FieldNumber_Quant = 4,
};

GPB_FINAL @interface ExchangeWithdrawContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite) int64_t exchangeId;

@property(nonatomic, readwrite, copy, null_resettable) NSData *tokenId;

@property(nonatomic, readwrite) int64_t quant;

@end

#pragma mark - ExchangeTransactionContract

typedef GPB_ENUM(ExchangeTransactionContract_FieldNumber) {
    ExchangeTransactionContract_FieldNumber_OwnerAddress = 1,
    ExchangeTransactionContract_FieldNumber_ExchangeId = 2,
    ExchangeTransactionContract_FieldNumber_TokenId = 3,
    ExchangeTransactionContract_FieldNumber_Quant = 4,
    ExchangeTransactionContract_FieldNumber_Expected = 5,
};

GPB_FINAL @interface ExchangeTransactionContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite) int64_t exchangeId;

@property(nonatomic, readwrite, copy, null_resettable) NSData *tokenId;

@property(nonatomic, readwrite) int64_t quant;

@property(nonatomic, readwrite) int64_t expected;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
