// Generated by the protocol buffer compiler.  DO NOT EDIT!
// clang-format off
// source: core/contract/proposal_contract.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
#define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
#import <Protobuf/GPBProtocolBuffers.h>
#else
#import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ProposalContractRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ProposalContractRoot : GPBRootObject
@end

#pragma mark - ProposalApproveContract

typedef GPB_ENUM(ProposalApproveContract_FieldNumber) {
    ProposalApproveContract_FieldNumber_OwnerAddress = 1,
    ProposalApproveContract_FieldNumber_ProposalId = 2,
    ProposalApproveContract_FieldNumber_IsAddApproval = 3,
};

GPB_FINAL @interface ProposalApproveContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite) int64_t proposalId;

/** add or remove approval */
@property(nonatomic, readwrite) BOOL isAddApproval;

@end

#pragma mark - ProposalCreateContract

typedef GPB_ENUM(ProposalCreateContract_FieldNumber) {
    ProposalCreateContract_FieldNumber_OwnerAddress = 1,
    ProposalCreateContract_FieldNumber_Parameters = 2,
};

GPB_FINAL @interface ProposalCreateContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Int64Dictionary *parameters;
/** The number of items in @c parameters without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger parameters_Count;

@end

#pragma mark - ProposalDeleteContract

typedef GPB_ENUM(ProposalDeleteContract_FieldNumber) {
    ProposalDeleteContract_FieldNumber_OwnerAddress = 1,
    ProposalDeleteContract_FieldNumber_ProposalId = 2,
};

GPB_FINAL @interface ProposalDeleteContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite) int64_t proposalId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
