// Generated by the protocol buffer compiler.  DO NOT EDIT!
// clang-format off
// source: core/contract/smart_contract.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
#define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
#import <Protobuf/GPBProtocolBuffers.h>
#else
#import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ContractState;
@class SmartContract;
@class SmartContract_ABI;
@class SmartContract_ABI_Entry;
@class SmartContract_ABI_Entry_Param;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum SmartContract_ABI_Entry_EntryType

typedef GPB_ENUM(SmartContract_ABI_Entry_EntryType) {
    /**
     * Value used if any message's field encounters a value that is not defined
     * by this enum. The message will also have C functions to get/set the rawValue
     * of the field.
     **/
    SmartContract_ABI_Entry_EntryType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
    SmartContract_ABI_Entry_EntryType_UnknownEntryType = 0,
    SmartContract_ABI_Entry_EntryType_Constructor = 1,
    SmartContract_ABI_Entry_EntryType_Function = 2,
    SmartContract_ABI_Entry_EntryType_Event = 3,
    SmartContract_ABI_Entry_EntryType_Fallback = 4,
    SmartContract_ABI_Entry_EntryType_Receive = 5,
    SmartContract_ABI_Entry_EntryType_Error = 6,
};

GPBEnumDescriptor *SmartContract_ABI_Entry_EntryType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL SmartContract_ABI_Entry_EntryType_IsValidValue(int32_t value);

#pragma mark - Enum SmartContract_ABI_Entry_StateMutabilityType

typedef GPB_ENUM(SmartContract_ABI_Entry_StateMutabilityType) {
    /**
     * Value used if any message's field encounters a value that is not defined
     * by this enum. The message will also have C functions to get/set the rawValue
     * of the field.
     **/
    SmartContract_ABI_Entry_StateMutabilityType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
    SmartContract_ABI_Entry_StateMutabilityType_UnknownMutabilityType = 0,
    SmartContract_ABI_Entry_StateMutabilityType_Pure = 1,
    SmartContract_ABI_Entry_StateMutabilityType_View = 2,
    SmartContract_ABI_Entry_StateMutabilityType_Nonpayable = 3,
    SmartContract_ABI_Entry_StateMutabilityType_Payable = 4,
};

GPBEnumDescriptor *SmartContract_ABI_Entry_StateMutabilityType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL SmartContract_ABI_Entry_StateMutabilityType_IsValidValue(int32_t value);

#pragma mark - SmartContractRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface SmartContractRoot : GPBRootObject
@end

#pragma mark - SmartContract

typedef GPB_ENUM(SmartContract_FieldNumber) {
    SmartContract_FieldNumber_OriginAddress = 1,
    SmartContract_FieldNumber_ContractAddress = 2,
    SmartContract_FieldNumber_Abi = 3,
    SmartContract_FieldNumber_Bytecode = 4,
    SmartContract_FieldNumber_CallValue = 5,
    SmartContract_FieldNumber_ConsumeUserResourcePercent = 6,
    SmartContract_FieldNumber_Name = 7,
    SmartContract_FieldNumber_OriginEnergyLimit = 8,
    SmartContract_FieldNumber_CodeHash = 9,
    SmartContract_FieldNumber_TrxHash = 10,
    SmartContract_FieldNumber_Version = 11,
};

GPB_FINAL @interface SmartContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *originAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSData *contractAddress;

@property(nonatomic, readwrite, strong, null_resettable) SmartContract_ABI *abi;
/** Test to see if @c abi has been set. */
@property(nonatomic, readwrite) BOOL hasAbi;

@property(nonatomic, readwrite, copy, null_resettable) NSData *bytecode;

@property(nonatomic, readwrite) int64_t callValue;

@property(nonatomic, readwrite) int64_t consumeUserResourcePercent;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) int64_t originEnergyLimit;

@property(nonatomic, readwrite, copy, null_resettable) NSData *codeHash;

@property(nonatomic, readwrite, copy, null_resettable) NSData *trxHash;

@property(nonatomic, readwrite) int32_t version;

@end

#pragma mark - SmartContract_ABI

typedef GPB_ENUM(SmartContract_ABI_FieldNumber) {
    SmartContract_ABI_FieldNumber_EntrysArray = 1,
};

GPB_FINAL @interface SmartContract_ABI : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SmartContract_ABI_Entry*> *entrysArray;
/** The number of items in @c entrysArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger entrysArray_Count;

@end

#pragma mark - SmartContract_ABI_Entry

typedef GPB_ENUM(SmartContract_ABI_Entry_FieldNumber) {
    SmartContract_ABI_Entry_FieldNumber_Anonymous = 1,
    SmartContract_ABI_Entry_FieldNumber_Constant = 2,
    SmartContract_ABI_Entry_FieldNumber_Name = 3,
    SmartContract_ABI_Entry_FieldNumber_InputsArray = 4,
    SmartContract_ABI_Entry_FieldNumber_OutputsArray = 5,
    SmartContract_ABI_Entry_FieldNumber_Type = 6,
    SmartContract_ABI_Entry_FieldNumber_Payable = 7,
    SmartContract_ABI_Entry_FieldNumber_StateMutability = 8,
};

GPB_FINAL @interface SmartContract_ABI_Entry : GPBMessage

@property(nonatomic, readwrite) BOOL anonymous;

@property(nonatomic, readwrite) BOOL constant;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SmartContract_ABI_Entry_Param*> *inputsArray;
/** The number of items in @c inputsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger inputsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SmartContract_ABI_Entry_Param*> *outputsArray;
/** The number of items in @c outputsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger outputsArray_Count;

@property(nonatomic, readwrite) SmartContract_ABI_Entry_EntryType type;

@property(nonatomic, readwrite) BOOL payable;

@property(nonatomic, readwrite) SmartContract_ABI_Entry_StateMutabilityType stateMutability;

@end

/**
 * Fetches the raw value of a @c SmartContract_ABI_Entry's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t SmartContract_ABI_Entry_Type_RawValue(SmartContract_ABI_Entry *message);
/**
 * Sets the raw value of an @c SmartContract_ABI_Entry's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetSmartContract_ABI_Entry_Type_RawValue(SmartContract_ABI_Entry *message, int32_t value);

/**
 * Fetches the raw value of a @c SmartContract_ABI_Entry's @c stateMutability property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t SmartContract_ABI_Entry_StateMutability_RawValue(SmartContract_ABI_Entry *message);
/**
 * Sets the raw value of an @c SmartContract_ABI_Entry's @c stateMutability property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetSmartContract_ABI_Entry_StateMutability_RawValue(SmartContract_ABI_Entry *message, int32_t value);

#pragma mark - SmartContract_ABI_Entry_Param

typedef GPB_ENUM(SmartContract_ABI_Entry_Param_FieldNumber) {
    SmartContract_ABI_Entry_Param_FieldNumber_Indexed = 1,
    SmartContract_ABI_Entry_Param_FieldNumber_Name = 2,
    SmartContract_ABI_Entry_Param_FieldNumber_Type = 3,
};

GPB_FINAL @interface SmartContract_ABI_Entry_Param : GPBMessage

@property(nonatomic, readwrite) BOOL indexed;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** SolidityType type = 3; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@end

#pragma mark - ContractState

typedef GPB_ENUM(ContractState_FieldNumber) {
    ContractState_FieldNumber_EnergyUsage = 1,
    ContractState_FieldNumber_EnergyFactor = 2,
    ContractState_FieldNumber_UpdateCycle = 3,
};

GPB_FINAL @interface ContractState : GPBMessage

@property(nonatomic, readwrite) int64_t energyUsage;

@property(nonatomic, readwrite) int64_t energyFactor;

@property(nonatomic, readwrite) int64_t updateCycle;

@end

#pragma mark - CreateSmartContract

typedef GPB_ENUM(CreateSmartContract_FieldNumber) {
    CreateSmartContract_FieldNumber_OwnerAddress = 1,
    CreateSmartContract_FieldNumber_NewContract = 2,
    CreateSmartContract_FieldNumber_CallTokenValue = 3,
    CreateSmartContract_FieldNumber_TokenId = 4,
};

GPB_FINAL @interface CreateSmartContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite, strong, null_resettable) SmartContract *newContract NS_RETURNS_NOT_RETAINED;
/** Test to see if @c newContract has been set. */
@property(nonatomic, readwrite) BOOL hasNewContract;

@property(nonatomic, readwrite) int64_t callTokenValue;

@property(nonatomic, readwrite) int64_t tokenId;

@end

#pragma mark - TriggerSmartContract

typedef GPB_ENUM(TriggerSmartContract_FieldNumber) {
    TriggerSmartContract_FieldNumber_OwnerAddress = 1,
    TriggerSmartContract_FieldNumber_ContractAddress = 2,
    TriggerSmartContract_FieldNumber_CallValue = 3,
    TriggerSmartContract_FieldNumber_Data_p = 4,
    TriggerSmartContract_FieldNumber_CallTokenValue = 5,
    TriggerSmartContract_FieldNumber_TokenId = 6,
};

GPB_FINAL @interface TriggerSmartContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSData *contractAddress;

@property(nonatomic, readwrite) int64_t callValue;

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@property(nonatomic, readwrite) int64_t callTokenValue;

@property(nonatomic, readwrite) int64_t tokenId;

@end

#pragma mark - ClearABIContract

typedef GPB_ENUM(ClearABIContract_FieldNumber) {
    ClearABIContract_FieldNumber_OwnerAddress = 1,
    ClearABIContract_FieldNumber_ContractAddress = 2,
};

GPB_FINAL @interface ClearABIContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSData *contractAddress;

@end

#pragma mark - UpdateSettingContract

typedef GPB_ENUM(UpdateSettingContract_FieldNumber) {
    UpdateSettingContract_FieldNumber_OwnerAddress = 1,
    UpdateSettingContract_FieldNumber_ContractAddress = 2,
    UpdateSettingContract_FieldNumber_ConsumeUserResourcePercent = 3,
};

GPB_FINAL @interface UpdateSettingContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSData *contractAddress;

@property(nonatomic, readwrite) int64_t consumeUserResourcePercent;

@end

#pragma mark - UpdateEnergyLimitContract

typedef GPB_ENUM(UpdateEnergyLimitContract_FieldNumber) {
    UpdateEnergyLimitContract_FieldNumber_OwnerAddress = 1,
    UpdateEnergyLimitContract_FieldNumber_ContractAddress = 2,
    UpdateEnergyLimitContract_FieldNumber_OriginEnergyLimit = 3,
};

GPB_FINAL @interface UpdateEnergyLimitContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSData *contractAddress;

@property(nonatomic, readwrite) int64_t originEnergyLimit;

@end

#pragma mark - SmartContractDataWrapper

typedef GPB_ENUM(SmartContractDataWrapper_FieldNumber) {
    SmartContractDataWrapper_FieldNumber_SmartContract = 1,
    SmartContractDataWrapper_FieldNumber_Runtimecode = 2,
    SmartContractDataWrapper_FieldNumber_ContractState = 3,
};

GPB_FINAL @interface SmartContractDataWrapper : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) SmartContract *smartContract;
/** Test to see if @c smartContract has been set. */
@property(nonatomic, readwrite) BOOL hasSmartContract;

@property(nonatomic, readwrite, copy, null_resettable) NSData *runtimecode;

@property(nonatomic, readwrite, strong, null_resettable) ContractState *contractState;
/** Test to see if @c contractState has been set. */
@property(nonatomic, readwrite) BOOL hasContractState;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
