// Generated by the protocol buffer compiler.  DO NOT EDIT!
// clang-format off
// source: core/contract/witness_contract.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
#define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
#import <Protobuf/GPBProtocolBuffers.h>
#else
#import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class VoteWitnessContract_Vote;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - WitnessContractRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface WitnessContractRoot : GPBRootObject
@end

#pragma mark - WitnessCreateContract

typedef GPB_ENUM(WitnessCreateContract_FieldNumber) {
    WitnessCreateContract_FieldNumber_OwnerAddress = 1,
    WitnessCreateContract_FieldNumber_URL = 2,
};

GPB_FINAL @interface WitnessCreateContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSData *URL;

@end

#pragma mark - WitnessUpdateContract

typedef GPB_ENUM(WitnessUpdateContract_FieldNumber) {
    WitnessUpdateContract_FieldNumber_OwnerAddress = 1,
    WitnessUpdateContract_FieldNumber_UpdateURL = 12,
};

GPB_FINAL @interface WitnessUpdateContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSData *updateURL;

@end

#pragma mark - VoteWitnessContract

typedef GPB_ENUM(VoteWitnessContract_FieldNumber) {
    VoteWitnessContract_FieldNumber_OwnerAddress = 1,
    VoteWitnessContract_FieldNumber_VotesArray = 2,
    VoteWitnessContract_FieldNumber_Support = 3,
};

GPB_FINAL @interface VoteWitnessContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<VoteWitnessContract_Vote*> *votesArray;
/** The number of items in @c votesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger votesArray_Count;

@property(nonatomic, readwrite) BOOL support;

@end

#pragma mark - VoteWitnessContract_Vote

typedef GPB_ENUM(VoteWitnessContract_Vote_FieldNumber) {
    VoteWitnessContract_Vote_FieldNumber_VoteAddress = 1,
    VoteWitnessContract_Vote_FieldNumber_VoteCount = 2,
};

GPB_FINAL @interface VoteWitnessContract_Vote : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *voteAddress;

@property(nonatomic, readwrite) int64_t voteCount;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
