// Generated by the protocol buffer compiler.  DO NOT EDIT!
// clang-format off
// source: api/api.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
#define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
#import <Protobuf/GPBProtocolBuffers.h>
#else
#import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class TronAccount;
@class Address;
@class AssetIssueContract;
@class Block;
@class BlockExtention;
@class BlockHeader;
@class BytesMessage;
@class DecryptNotesMarked_NoteTx;
@class DecryptNotesTRC20_NoteTx;
@class DecryptNotes_NoteTx;
@class DelegatedResource;
@class DiversifierMessage;
@class Exchange;
@class IncomingViewingKeyMessage;
@class IncrementalMerkleTree;
@class IncrementalMerkleVoucher;
@class InternalTransaction;
@class Node;
@class Note;
@class Permission;
@class Proposal;
@class ReceiveDescription;
@class ReceiveNote;
@class Return;
@class ShieldedTRC20Parameters;
@class SpendDescription;
@class SpendNote;
@class SpendNoteTRC20;
@class TimeMessage;
@class TronTransaction;
@class TransactionApprovedList_Result;
@class TransactionExtention;
@class TransactionInfo;
@class TransactionInfo_Log;
@class TransactionSignWeight_Result;
@class Witness;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Return_response_code

typedef GPB_ENUM(Return_response_code) {
    /**
     * Value used if any message's field encounters a value that is not defined
     * by this enum. The message will also have C functions to get/set the rawValue
     * of the field.
     **/
    Return_response_code_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
    Return_response_code_Success = 0,
    
    /** error in signature */
    Return_response_code_Sigerror = 1,
    Return_response_code_ContractValidateError = 2,
    Return_response_code_ContractExeError = 3,
    Return_response_code_BandwithError = 4,
    Return_response_code_DupTransactionError = 5,
    Return_response_code_TaposError = 6,
    Return_response_code_TooBigTransactionError = 7,
    Return_response_code_TransactionExpirationError = 8,
    Return_response_code_ServerBusy = 9,
    Return_response_code_NoConnection = 10,
    Return_response_code_NotEnoughEffectiveConnection = 11,
    Return_response_code_OtherError = 20,
};

GPBEnumDescriptor *Return_response_code_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Return_response_code_IsValidValue(int32_t value);

#pragma mark - Enum TransactionSignWeight_Result_response_code

typedef GPB_ENUM(TransactionSignWeight_Result_response_code) {
    /**
     * Value used if any message's field encounters a value that is not defined
     * by this enum. The message will also have C functions to get/set the rawValue
     * of the field.
     **/
    TransactionSignWeight_Result_response_code_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
    TransactionSignWeight_Result_response_code_EnoughPermission = 0,
    
    /** error in */
    TransactionSignWeight_Result_response_code_NotEnoughPermission = 1,
    TransactionSignWeight_Result_response_code_SignatureFormatError = 2,
    TransactionSignWeight_Result_response_code_ComputeAddressError = 3,
    
    /** The key is not in permission */
    TransactionSignWeight_Result_response_code_PermissionError = 4,
    TransactionSignWeight_Result_response_code_OtherError = 20,
};

GPBEnumDescriptor *TransactionSignWeight_Result_response_code_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL TransactionSignWeight_Result_response_code_IsValidValue(int32_t value);

#pragma mark - Enum TransactionApprovedList_Result_response_code

typedef GPB_ENUM(TransactionApprovedList_Result_response_code) {
    /**
     * Value used if any message's field encounters a value that is not defined
     * by this enum. The message will also have C functions to get/set the rawValue
     * of the field.
     **/
    TransactionApprovedList_Result_response_code_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
    TransactionApprovedList_Result_response_code_Success = 0,
    TransactionApprovedList_Result_response_code_SignatureFormatError = 1,
    TransactionApprovedList_Result_response_code_ComputeAddressError = 2,
    TransactionApprovedList_Result_response_code_OtherError = 20,
};

GPBEnumDescriptor *TransactionApprovedList_Result_response_code_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL TransactionApprovedList_Result_response_code_IsValidValue(int32_t value);

#pragma mark - ApiRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ApiRoot : GPBRootObject
@end

#pragma mark - Return

typedef GPB_ENUM(Return_FieldNumber) {
    Return_FieldNumber_Result = 1,
    Return_FieldNumber_Code = 2,
    Return_FieldNumber_Message = 3,
};

GPB_FINAL @interface Return : GPBMessage

@property(nonatomic, readwrite) BOOL result;

@property(nonatomic, readwrite) Return_response_code code;

@property(nonatomic, readwrite, copy, null_resettable) NSData *message;

@end

/**
 * Fetches the raw value of a @c Return's @c code property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Return_Code_RawValue(Return *message);
/**
 * Sets the raw value of an @c Return's @c code property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetReturn_Code_RawValue(Return *message, int32_t value);

#pragma mark - BlockReference

typedef GPB_ENUM(BlockReference_FieldNumber) {
    BlockReference_FieldNumber_BlockNum = 1,
    BlockReference_FieldNumber_BlockHash = 2,
};

GPB_FINAL @interface BlockReference : GPBMessage

@property(nonatomic, readwrite) int64_t blockNum;

@property(nonatomic, readwrite, copy, null_resettable) NSData *blockHash;

@end

#pragma mark - WitnessList

typedef GPB_ENUM(WitnessList_FieldNumber) {
    WitnessList_FieldNumber_WitnessesArray = 1,
};

GPB_FINAL @interface WitnessList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Witness*> *witnessesArray;
/** The number of items in @c witnessesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger witnessesArray_Count;

@end

#pragma mark - ProposalList

typedef GPB_ENUM(ProposalList_FieldNumber) {
    ProposalList_FieldNumber_ProposalsArray = 1,
};

GPB_FINAL @interface ProposalList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Proposal*> *proposalsArray;
/** The number of items in @c proposalsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger proposalsArray_Count;

@end

#pragma mark - ExchangeList

typedef GPB_ENUM(ExchangeList_FieldNumber) {
    ExchangeList_FieldNumber_ExchangesArray = 1,
};

GPB_FINAL @interface ExchangeList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Exchange*> *exchangesArray;
/** The number of items in @c exchangesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger exchangesArray_Count;

@end

#pragma mark - AssetIssueList

typedef GPB_ENUM(AssetIssueList_FieldNumber) {
    AssetIssueList_FieldNumber_AssetIssueArray = 1,
};

GPB_FINAL @interface AssetIssueList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<AssetIssueContract*> *assetIssueArray;
/** The number of items in @c assetIssueArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger assetIssueArray_Count;

@end

#pragma mark - BlockList

typedef GPB_ENUM(BlockList_FieldNumber) {
    BlockList_FieldNumber_BlockArray = 1,
};

GPB_FINAL @interface BlockList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Block*> *blockArray;
/** The number of items in @c blockArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger blockArray_Count;

@end

#pragma mark - TransactionList

typedef GPB_ENUM(TransactionList_FieldNumber) {
    TransactionList_FieldNumber_TransactionArray = 1,
};

GPB_FINAL @interface TransactionList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TronTransaction*> *transactionArray;
/** The number of items in @c transactionArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger transactionArray_Count;

@end

#pragma mark - TransactionIdList

typedef GPB_ENUM(TransactionIdList_FieldNumber) {
    TransactionIdList_FieldNumber_TxIdArray = 1,
};

GPB_FINAL @interface TransactionIdList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *txIdArray;
/** The number of items in @c txIdArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger txIdArray_Count;

@end

#pragma mark - DelegatedResourceMessage

typedef GPB_ENUM(DelegatedResourceMessage_FieldNumber) {
    DelegatedResourceMessage_FieldNumber_FromAddress = 1,
    DelegatedResourceMessage_FieldNumber_ToAddress = 2,
};

GPB_FINAL @interface DelegatedResourceMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *fromAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSData *toAddress;

@end

#pragma mark - DelegatedResourceList

typedef GPB_ENUM(DelegatedResourceList_FieldNumber) {
    DelegatedResourceList_FieldNumber_DelegatedResourceArray = 1,
};

GPB_FINAL @interface DelegatedResourceList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DelegatedResource*> *delegatedResourceArray;
/** The number of items in @c delegatedResourceArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger delegatedResourceArray_Count;

@end

#pragma mark - GetAvailableUnfreezeCountRequestMessage

typedef GPB_ENUM(GetAvailableUnfreezeCountRequestMessage_FieldNumber) {
    GetAvailableUnfreezeCountRequestMessage_FieldNumber_OwnerAddress = 1,
};

GPB_FINAL @interface GetAvailableUnfreezeCountRequestMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@end

#pragma mark - GetAvailableUnfreezeCountResponseMessage

typedef GPB_ENUM(GetAvailableUnfreezeCountResponseMessage_FieldNumber) {
    GetAvailableUnfreezeCountResponseMessage_FieldNumber_Count = 1,
};

GPB_FINAL @interface GetAvailableUnfreezeCountResponseMessage : GPBMessage

@property(nonatomic, readwrite) int64_t count;

@end

#pragma mark - CanDelegatedMaxSizeRequestMessage

typedef GPB_ENUM(CanDelegatedMaxSizeRequestMessage_FieldNumber) {
    CanDelegatedMaxSizeRequestMessage_FieldNumber_Type = 1,
    CanDelegatedMaxSizeRequestMessage_FieldNumber_OwnerAddress = 2,
};

GPB_FINAL @interface CanDelegatedMaxSizeRequestMessage : GPBMessage

@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@end

#pragma mark - CanDelegatedMaxSizeResponseMessage

typedef GPB_ENUM(CanDelegatedMaxSizeResponseMessage_FieldNumber) {
    CanDelegatedMaxSizeResponseMessage_FieldNumber_MaxSize = 1,
};

GPB_FINAL @interface CanDelegatedMaxSizeResponseMessage : GPBMessage

@property(nonatomic, readwrite) int64_t maxSize;

@end

#pragma mark - CanWithdrawUnfreezeAmountRequestMessage

typedef GPB_ENUM(CanWithdrawUnfreezeAmountRequestMessage_FieldNumber) {
    CanWithdrawUnfreezeAmountRequestMessage_FieldNumber_OwnerAddress = 1,
    CanWithdrawUnfreezeAmountRequestMessage_FieldNumber_Timestamp = 2,
};

GPB_FINAL @interface CanWithdrawUnfreezeAmountRequestMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite) int64_t timestamp;

@end

#pragma mark - CanWithdrawUnfreezeAmountResponseMessage

typedef GPB_ENUM(CanWithdrawUnfreezeAmountResponseMessage_FieldNumber) {
    CanWithdrawUnfreezeAmountResponseMessage_FieldNumber_Amount = 1,
};

GPB_FINAL @interface CanWithdrawUnfreezeAmountResponseMessage : GPBMessage

@property(nonatomic, readwrite) int64_t amount;

@end

#pragma mark - NodeList

typedef GPB_ENUM(NodeList_FieldNumber) {
    NodeList_FieldNumber_NodesArray = 1,
};

/**
 * Gossip node list
 **/
GPB_FINAL @interface NodeList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Node*> *nodesArray;
/** The number of items in @c nodesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger nodesArray_Count;

@end

#pragma mark - Node

typedef GPB_ENUM(Node_FieldNumber) {
    Node_FieldNumber_Address = 1,
};

/**
 * Gossip node
 **/
GPB_FINAL @interface Node : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Address *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

@end

#pragma mark - Address

typedef GPB_ENUM(Address_FieldNumber) {
    Address_FieldNumber_Host = 1,
    Address_FieldNumber_Port = 2,
};

/**
 * Gossip node address
 **/
GPB_FINAL @interface Address : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *host;

@property(nonatomic, readwrite) int32_t port;

@end

#pragma mark - EmptyMessage

GPB_FINAL @interface EmptyMessage : GPBMessage

@end

#pragma mark - NumberMessage

typedef GPB_ENUM(NumberMessage_FieldNumber) {
    NumberMessage_FieldNumber_Num = 1,
};

GPB_FINAL @interface NumberMessage : GPBMessage

@property(nonatomic, readwrite) int64_t num;

@end

#pragma mark - BytesMessage

typedef GPB_ENUM(BytesMessage_FieldNumber) {
    BytesMessage_FieldNumber_Value = 1,
};

GPB_FINAL @interface BytesMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *value;

@end

#pragma mark - TimeMessage

typedef GPB_ENUM(TimeMessage_FieldNumber) {
    TimeMessage_FieldNumber_BeginInMilliseconds = 1,
    TimeMessage_FieldNumber_EndInMilliseconds = 2,
};

GPB_FINAL @interface TimeMessage : GPBMessage

@property(nonatomic, readwrite) int64_t beginInMilliseconds;

@property(nonatomic, readwrite) int64_t endInMilliseconds;

@end

#pragma mark - BlockReq

typedef GPB_ENUM(BlockReq_FieldNumber) {
    BlockReq_FieldNumber_IdOrNum = 1,
    BlockReq_FieldNumber_Detail = 2,
};

GPB_FINAL @interface BlockReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *idOrNum;

@property(nonatomic, readwrite) BOOL detail;

@end

#pragma mark - BlockLimit

typedef GPB_ENUM(BlockLimit_FieldNumber) {
    BlockLimit_FieldNumber_StartNum = 1,
    BlockLimit_FieldNumber_EndNum = 2,
};

GPB_FINAL @interface BlockLimit : GPBMessage

@property(nonatomic, readwrite) int64_t startNum;

@property(nonatomic, readwrite) int64_t endNum;

@end

#pragma mark - TransactionLimit

typedef GPB_ENUM(TransactionLimit_FieldNumber) {
    TransactionLimit_FieldNumber_TransactionId = 1,
    TransactionLimit_FieldNumber_LimitNum = 2,
};

GPB_FINAL @interface TransactionLimit : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *transactionId;

@property(nonatomic, readwrite) int64_t limitNum;

@end

#pragma mark - AccountPaginated

typedef GPB_ENUM(AccountPaginated_FieldNumber) {
    AccountPaginated_FieldNumber_Account = 1,
    AccountPaginated_FieldNumber_Offset = 2,
    AccountPaginated_FieldNumber_Limit = 3,
};

GPB_FINAL @interface AccountPaginated : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) TronAccount *account;
/** Test to see if @c account has been set. */
@property(nonatomic, readwrite) BOOL hasAccount;

@property(nonatomic, readwrite) int64_t offset;

@property(nonatomic, readwrite) int64_t limit;

@end

#pragma mark - TimePaginatedMessage

typedef GPB_ENUM(TimePaginatedMessage_FieldNumber) {
    TimePaginatedMessage_FieldNumber_TimeMessage = 1,
    TimePaginatedMessage_FieldNumber_Offset = 2,
    TimePaginatedMessage_FieldNumber_Limit = 3,
};

GPB_FINAL @interface TimePaginatedMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) TimeMessage *timeMessage;
/** Test to see if @c timeMessage has been set. */
@property(nonatomic, readwrite) BOOL hasTimeMessage;

@property(nonatomic, readwrite) int64_t offset;

@property(nonatomic, readwrite) int64_t limit;

@end

#pragma mark - AccountNetMessage

typedef GPB_ENUM(AccountNetMessage_FieldNumber) {
    AccountNetMessage_FieldNumber_FreeNetUsed = 1,
    AccountNetMessage_FieldNumber_FreeNetLimit = 2,
    AccountNetMessage_FieldNumber_NetUsed = 3,
    AccountNetMessage_FieldNumber_NetLimit = 4,
    AccountNetMessage_FieldNumber_AssetNetUsed = 5,
    AccountNetMessage_FieldNumber_AssetNetLimit = 6,
    AccountNetMessage_FieldNumber_TotalNetLimit = 7,
    AccountNetMessage_FieldNumber_TotalNetWeight = 8,
};

/**
 * deprecated
 **/
GPB_FINAL @interface AccountNetMessage : GPBMessage

@property(nonatomic, readwrite) int64_t freeNetUsed;

@property(nonatomic, readwrite) int64_t freeNetLimit;

@property(nonatomic, readwrite) int64_t netUsed;

@property(nonatomic, readwrite) int64_t netLimit;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt64Dictionary *assetNetUsed;
/** The number of items in @c assetNetUsed without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger assetNetUsed_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt64Dictionary *assetNetLimit;
/** The number of items in @c assetNetLimit without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger assetNetLimit_Count;

@property(nonatomic, readwrite) int64_t totalNetLimit;

@property(nonatomic, readwrite) int64_t totalNetWeight;

@end

#pragma mark - AccountResourceMessage

typedef GPB_ENUM(AccountResourceMessage_FieldNumber) {
    AccountResourceMessage_FieldNumber_FreeNetUsed = 1,
    AccountResourceMessage_FieldNumber_FreeNetLimit = 2,
    AccountResourceMessage_FieldNumber_NetUsed = 3,
    AccountResourceMessage_FieldNumber_NetLimit = 4,
    AccountResourceMessage_FieldNumber_AssetNetUsed = 5,
    AccountResourceMessage_FieldNumber_AssetNetLimit = 6,
    AccountResourceMessage_FieldNumber_TotalNetLimit = 7,
    AccountResourceMessage_FieldNumber_TotalNetWeight = 8,
    AccountResourceMessage_FieldNumber_TotalTronPowerWeight = 9,
    AccountResourceMessage_FieldNumber_TronPowerUsed = 10,
    AccountResourceMessage_FieldNumber_TronPowerLimit = 11,
    AccountResourceMessage_FieldNumber_EnergyUsed = 13,
    AccountResourceMessage_FieldNumber_EnergyLimit = 14,
    AccountResourceMessage_FieldNumber_TotalEnergyLimit = 15,
    AccountResourceMessage_FieldNumber_TotalEnergyWeight = 16,
    AccountResourceMessage_FieldNumber_StorageUsed = 21,
    AccountResourceMessage_FieldNumber_StorageLimit = 22,
};

GPB_FINAL @interface AccountResourceMessage : GPBMessage

@property(nonatomic, readwrite) int64_t freeNetUsed;

@property(nonatomic, readwrite) int64_t freeNetLimit;

@property(nonatomic, readwrite) int64_t netUsed;

@property(nonatomic, readwrite) int64_t netLimit;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt64Dictionary *assetNetUsed;
/** The number of items in @c assetNetUsed without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger assetNetUsed_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt64Dictionary *assetNetLimit;
/** The number of items in @c assetNetLimit without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger assetNetLimit_Count;

@property(nonatomic, readwrite) int64_t totalNetLimit;

@property(nonatomic, readwrite) int64_t totalNetWeight;

@property(nonatomic, readwrite) int64_t totalTronPowerWeight;

@property(nonatomic, readwrite) int64_t tronPowerUsed;

@property(nonatomic, readwrite) int64_t tronPowerLimit;

@property(nonatomic, readwrite) int64_t energyUsed;

@property(nonatomic, readwrite) int64_t energyLimit;

@property(nonatomic, readwrite) int64_t totalEnergyLimit;

@property(nonatomic, readwrite) int64_t totalEnergyWeight;

@property(nonatomic, readwrite) int64_t storageUsed;

@property(nonatomic, readwrite) int64_t storageLimit;

@end

#pragma mark - PaginatedMessage

typedef GPB_ENUM(PaginatedMessage_FieldNumber) {
    PaginatedMessage_FieldNumber_Offset = 1,
    PaginatedMessage_FieldNumber_Limit = 2,
};

GPB_FINAL @interface PaginatedMessage : GPBMessage

@property(nonatomic, readwrite) int64_t offset;

@property(nonatomic, readwrite) int64_t limit;

@end

#pragma mark - TransactionExtention

typedef GPB_ENUM(TransactionExtention_FieldNumber) {
    TransactionExtention_FieldNumber_Transaction = 1,
    TransactionExtention_FieldNumber_Txid = 2,
    TransactionExtention_FieldNumber_ConstantResultArray = 3,
    TransactionExtention_FieldNumber_Result = 4,
    TransactionExtention_FieldNumber_EnergyUsed = 5,
    TransactionExtention_FieldNumber_LogsArray = 6,
    TransactionExtention_FieldNumber_InternalTransactionsArray = 7,
    TransactionExtention_FieldNumber_EnergyPenalty = 8,
};

GPB_FINAL @interface TransactionExtention : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) TronTransaction *transaction;
/** Test to see if @c transaction has been set. */
@property(nonatomic, readwrite) BOOL hasTransaction;

/** transaction id =  sha256(transaction.rowdata) */
@property(nonatomic, readwrite, copy, null_resettable) NSData *txid;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSData*> *constantResultArray;
/** The number of items in @c constantResultArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger constantResultArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) Return *result;
/** Test to see if @c result has been set. */
@property(nonatomic, readwrite) BOOL hasResult;

@property(nonatomic, readwrite) int64_t energyUsed;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TransactionInfo_Log*> *logsArray;
/** The number of items in @c logsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger logsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<InternalTransaction*> *internalTransactionsArray;
/** The number of items in @c internalTransactionsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger internalTransactionsArray_Count;

@property(nonatomic, readwrite) int64_t energyPenalty;

@end

#pragma mark - EstimateEnergyMessage

typedef GPB_ENUM(EstimateEnergyMessage_FieldNumber) {
    EstimateEnergyMessage_FieldNumber_Result = 1,
    EstimateEnergyMessage_FieldNumber_EnergyRequired = 2,
};

GPB_FINAL @interface EstimateEnergyMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Return *result;
/** Test to see if @c result has been set. */
@property(nonatomic, readwrite) BOOL hasResult;

@property(nonatomic, readwrite) int64_t energyRequired;

@end

#pragma mark - BlockExtention

typedef GPB_ENUM(BlockExtention_FieldNumber) {
    BlockExtention_FieldNumber_TransactionsArray = 1,
    BlockExtention_FieldNumber_BlockHeader = 2,
    BlockExtention_FieldNumber_Blockid = 3,
};

GPB_FINAL @interface BlockExtention : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TransactionExtention*> *transactionsArray;
/** The number of items in @c transactionsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger transactionsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) BlockHeader *blockHeader;
/** Test to see if @c blockHeader has been set. */
@property(nonatomic, readwrite) BOOL hasBlockHeader;

@property(nonatomic, readwrite, copy, null_resettable) NSData *blockid;

@end

#pragma mark - BlockListExtention

typedef GPB_ENUM(BlockListExtention_FieldNumber) {
    BlockListExtention_FieldNumber_BlockArray = 1,
};

GPB_FINAL @interface BlockListExtention : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BlockExtention*> *blockArray;
/** The number of items in @c blockArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger blockArray_Count;

@end

#pragma mark - TransactionListExtention

typedef GPB_ENUM(TransactionListExtention_FieldNumber) {
    TransactionListExtention_FieldNumber_TransactionArray = 1,
};

GPB_FINAL @interface TransactionListExtention : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TransactionExtention*> *transactionArray;
/** The number of items in @c transactionArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger transactionArray_Count;

@end

#pragma mark - BlockIncrementalMerkleTree

typedef GPB_ENUM(BlockIncrementalMerkleTree_FieldNumber) {
    BlockIncrementalMerkleTree_FieldNumber_Number = 1,
    BlockIncrementalMerkleTree_FieldNumber_MerkleTree = 2,
};

GPB_FINAL @interface BlockIncrementalMerkleTree : GPBMessage

@property(nonatomic, readwrite) int64_t number;

@property(nonatomic, readwrite, strong, null_resettable) IncrementalMerkleTree *merkleTree;
/** Test to see if @c merkleTree has been set. */
@property(nonatomic, readwrite) BOOL hasMerkleTree;

@end

#pragma mark - TransactionSignWeight

typedef GPB_ENUM(TransactionSignWeight_FieldNumber) {
    TransactionSignWeight_FieldNumber_Permission = 1,
    TransactionSignWeight_FieldNumber_ApprovedListArray = 2,
    TransactionSignWeight_FieldNumber_CurrentWeight = 3,
    TransactionSignWeight_FieldNumber_Result = 4,
    TransactionSignWeight_FieldNumber_Transaction = 5,
};

GPB_FINAL @interface TransactionSignWeight : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Permission *permission;
/** Test to see if @c permission has been set. */
@property(nonatomic, readwrite) BOOL hasPermission;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSData*> *approvedListArray;
/** The number of items in @c approvedListArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger approvedListArray_Count;

@property(nonatomic, readwrite) int64_t currentWeight;

@property(nonatomic, readwrite, strong, null_resettable) TransactionSignWeight_Result *result;
/** Test to see if @c result has been set. */
@property(nonatomic, readwrite) BOOL hasResult;

@property(nonatomic, readwrite, strong, null_resettable) TransactionExtention *transaction;
/** Test to see if @c transaction has been set. */
@property(nonatomic, readwrite) BOOL hasTransaction;

@end

#pragma mark - TransactionSignWeight_Result

typedef GPB_ENUM(TransactionSignWeight_Result_FieldNumber) {
    TransactionSignWeight_Result_FieldNumber_Code = 1,
    TransactionSignWeight_Result_FieldNumber_Message = 2,
};

GPB_FINAL @interface TransactionSignWeight_Result : GPBMessage

@property(nonatomic, readwrite) TransactionSignWeight_Result_response_code code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

/**
 * Fetches the raw value of a @c TransactionSignWeight_Result's @c code property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t TransactionSignWeight_Result_Code_RawValue(TransactionSignWeight_Result *message);
/**
 * Sets the raw value of an @c TransactionSignWeight_Result's @c code property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetTransactionSignWeight_Result_Code_RawValue(TransactionSignWeight_Result *message, int32_t value);

#pragma mark - TransactionApprovedList

typedef GPB_ENUM(TransactionApprovedList_FieldNumber) {
    TransactionApprovedList_FieldNumber_ApprovedListArray = 2,
    TransactionApprovedList_FieldNumber_Result = 4,
    TransactionApprovedList_FieldNumber_Transaction = 5,
};

GPB_FINAL @interface TransactionApprovedList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSData*> *approvedListArray;
/** The number of items in @c approvedListArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger approvedListArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) TransactionApprovedList_Result *result;
/** Test to see if @c result has been set. */
@property(nonatomic, readwrite) BOOL hasResult;

@property(nonatomic, readwrite, strong, null_resettable) TransactionExtention *transaction;
/** Test to see if @c transaction has been set. */
@property(nonatomic, readwrite) BOOL hasTransaction;

@end

#pragma mark - TransactionApprovedList_Result

typedef GPB_ENUM(TransactionApprovedList_Result_FieldNumber) {
    TransactionApprovedList_Result_FieldNumber_Code = 1,
    TransactionApprovedList_Result_FieldNumber_Message = 2,
};

GPB_FINAL @interface TransactionApprovedList_Result : GPBMessage

@property(nonatomic, readwrite) TransactionApprovedList_Result_response_code code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

/**
 * Fetches the raw value of a @c TransactionApprovedList_Result's @c code property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t TransactionApprovedList_Result_Code_RawValue(TransactionApprovedList_Result *message);
/**
 * Sets the raw value of an @c TransactionApprovedList_Result's @c code property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetTransactionApprovedList_Result_Code_RawValue(TransactionApprovedList_Result *message, int32_t value);

#pragma mark - IvkDecryptParameters

typedef GPB_ENUM(IvkDecryptParameters_FieldNumber) {
    IvkDecryptParameters_FieldNumber_StartBlockIndex = 1,
    IvkDecryptParameters_FieldNumber_EndBlockIndex = 2,
    IvkDecryptParameters_FieldNumber_Ivk = 3,
};

GPB_FINAL @interface IvkDecryptParameters : GPBMessage

@property(nonatomic, readwrite) int64_t startBlockIndex;

@property(nonatomic, readwrite) int64_t endBlockIndex;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ivk;

@end

#pragma mark - IvkDecryptAndMarkParameters

typedef GPB_ENUM(IvkDecryptAndMarkParameters_FieldNumber) {
    IvkDecryptAndMarkParameters_FieldNumber_StartBlockIndex = 1,
    IvkDecryptAndMarkParameters_FieldNumber_EndBlockIndex = 2,
    IvkDecryptAndMarkParameters_FieldNumber_Ak = 3,
    IvkDecryptAndMarkParameters_FieldNumber_Nk = 4,
    IvkDecryptAndMarkParameters_FieldNumber_Ivk = 5,
};

GPB_FINAL @interface IvkDecryptAndMarkParameters : GPBMessage

@property(nonatomic, readwrite) int64_t startBlockIndex;

@property(nonatomic, readwrite) int64_t endBlockIndex;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ivk;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ak;

@property(nonatomic, readwrite, copy, null_resettable) NSData *nk;

@end

#pragma mark - OvkDecryptParameters

typedef GPB_ENUM(OvkDecryptParameters_FieldNumber) {
    OvkDecryptParameters_FieldNumber_StartBlockIndex = 1,
    OvkDecryptParameters_FieldNumber_EndBlockIndex = 2,
    OvkDecryptParameters_FieldNumber_Ovk = 3,
};

GPB_FINAL @interface OvkDecryptParameters : GPBMessage

@property(nonatomic, readwrite) int64_t startBlockIndex;

@property(nonatomic, readwrite) int64_t endBlockIndex;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ovk;

@end

#pragma mark - DecryptNotes

typedef GPB_ENUM(DecryptNotes_FieldNumber) {
    DecryptNotes_FieldNumber_NoteTxsArray = 1,
};

GPB_FINAL @interface DecryptNotes : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DecryptNotes_NoteTx*> *noteTxsArray;
/** The number of items in @c noteTxsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger noteTxsArray_Count;

@end

#pragma mark - DecryptNotes_NoteTx

typedef GPB_ENUM(DecryptNotes_NoteTx_FieldNumber) {
    DecryptNotes_NoteTx_FieldNumber_Note = 1,
    DecryptNotes_NoteTx_FieldNumber_Txid = 2,
    DecryptNotes_NoteTx_FieldNumber_Index = 3,
};

GPB_FINAL @interface DecryptNotes_NoteTx : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Note *note;
/** Test to see if @c note has been set. */
@property(nonatomic, readwrite) BOOL hasNote;

/** transaction id =  sha256(transaction.rowdata) */
@property(nonatomic, readwrite, copy, null_resettable) NSData *txid;

/** the index of note in receive */
@property(nonatomic, readwrite) int32_t index;

@end

#pragma mark - DecryptNotesMarked

typedef GPB_ENUM(DecryptNotesMarked_FieldNumber) {
    DecryptNotesMarked_FieldNumber_NoteTxsArray = 1,
};

GPB_FINAL @interface DecryptNotesMarked : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DecryptNotesMarked_NoteTx*> *noteTxsArray;
/** The number of items in @c noteTxsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger noteTxsArray_Count;

@end

#pragma mark - DecryptNotesMarked_NoteTx

typedef GPB_ENUM(DecryptNotesMarked_NoteTx_FieldNumber) {
    DecryptNotesMarked_NoteTx_FieldNumber_Note = 1,
    DecryptNotesMarked_NoteTx_FieldNumber_Txid = 2,
    DecryptNotesMarked_NoteTx_FieldNumber_Index = 3,
    DecryptNotesMarked_NoteTx_FieldNumber_IsSpend = 4,
};

GPB_FINAL @interface DecryptNotesMarked_NoteTx : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Note *note;
/** Test to see if @c note has been set. */
@property(nonatomic, readwrite) BOOL hasNote;

/** transaction id =  sha256(transaction.rowdata) */
@property(nonatomic, readwrite, copy, null_resettable) NSData *txid;

/** the index of note in receive */
@property(nonatomic, readwrite) int32_t index;

@property(nonatomic, readwrite) BOOL isSpend;

@end

#pragma mark - Note

typedef GPB_ENUM(Note_FieldNumber) {
    Note_FieldNumber_Value = 1,
    Note_FieldNumber_PaymentAddress = 2,
    Note_FieldNumber_Rcm = 3,
    Note_FieldNumber_Memo = 4,
};

GPB_FINAL @interface Note : GPBMessage

@property(nonatomic, readwrite) int64_t value;

@property(nonatomic, readwrite, copy, null_resettable) NSString *paymentAddress;

/** random 32 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *rcm;

@property(nonatomic, readwrite, copy, null_resettable) NSData *memo;

@end

#pragma mark - SpendNote

typedef GPB_ENUM(SpendNote_FieldNumber) {
    SpendNote_FieldNumber_Note = 3,
    SpendNote_FieldNumber_Alpha = 4,
    SpendNote_FieldNumber_Voucher = 5,
    SpendNote_FieldNumber_Path = 6,
};

GPB_FINAL @interface SpendNote : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Note *note;
/** Test to see if @c note has been set. */
@property(nonatomic, readwrite) BOOL hasNote;

/** random number for spend authority signature */
@property(nonatomic, readwrite, copy, null_resettable) NSData *alpha;

@property(nonatomic, readwrite, strong, null_resettable) IncrementalMerkleVoucher *voucher;
/** Test to see if @c voucher has been set. */
@property(nonatomic, readwrite) BOOL hasVoucher;

/** path for cm from leaf to root in merkle tree */
@property(nonatomic, readwrite, copy, null_resettable) NSData *path;

@end

#pragma mark - ReceiveNote

typedef GPB_ENUM(ReceiveNote_FieldNumber) {
    ReceiveNote_FieldNumber_Note = 1,
};

GPB_FINAL @interface ReceiveNote : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Note *note;
/** Test to see if @c note has been set. */
@property(nonatomic, readwrite) BOOL hasNote;

@end

#pragma mark - PrivateParameters

typedef GPB_ENUM(PrivateParameters_FieldNumber) {
    PrivateParameters_FieldNumber_TransparentFromAddress = 1,
    PrivateParameters_FieldNumber_Ask = 2,
    PrivateParameters_FieldNumber_Nsk = 3,
    PrivateParameters_FieldNumber_Ovk = 4,
    PrivateParameters_FieldNumber_FromAmount = 5,
    PrivateParameters_FieldNumber_ShieldedSpendsArray = 6,
    PrivateParameters_FieldNumber_ShieldedReceivesArray = 7,
    PrivateParameters_FieldNumber_TransparentToAddress = 8,
    PrivateParameters_FieldNumber_ToAmount = 9,
    PrivateParameters_FieldNumber_Timeout = 10,
};

GPB_FINAL @interface PrivateParameters : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *transparentFromAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ask;

@property(nonatomic, readwrite, copy, null_resettable) NSData *nsk;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ovk;

@property(nonatomic, readwrite) int64_t fromAmount;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SpendNote*> *shieldedSpendsArray;
/** The number of items in @c shieldedSpendsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger shieldedSpendsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ReceiveNote*> *shieldedReceivesArray;
/** The number of items in @c shieldedReceivesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger shieldedReceivesArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSData *transparentToAddress;

@property(nonatomic, readwrite) int64_t toAmount;

/** timeout in seconds, it works only when it bigger than 0 */
@property(nonatomic, readwrite) int64_t timeout;

@end

#pragma mark - PrivateParametersWithoutAsk

typedef GPB_ENUM(PrivateParametersWithoutAsk_FieldNumber) {
    PrivateParametersWithoutAsk_FieldNumber_TransparentFromAddress = 1,
    PrivateParametersWithoutAsk_FieldNumber_Ak = 2,
    PrivateParametersWithoutAsk_FieldNumber_Nsk = 3,
    PrivateParametersWithoutAsk_FieldNumber_Ovk = 4,
    PrivateParametersWithoutAsk_FieldNumber_FromAmount = 5,
    PrivateParametersWithoutAsk_FieldNumber_ShieldedSpendsArray = 6,
    PrivateParametersWithoutAsk_FieldNumber_ShieldedReceivesArray = 7,
    PrivateParametersWithoutAsk_FieldNumber_TransparentToAddress = 8,
    PrivateParametersWithoutAsk_FieldNumber_ToAmount = 9,
    PrivateParametersWithoutAsk_FieldNumber_Timeout = 10,
};

GPB_FINAL @interface PrivateParametersWithoutAsk : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *transparentFromAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ak;

@property(nonatomic, readwrite, copy, null_resettable) NSData *nsk;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ovk;

@property(nonatomic, readwrite) int64_t fromAmount;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SpendNote*> *shieldedSpendsArray;
/** The number of items in @c shieldedSpendsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger shieldedSpendsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ReceiveNote*> *shieldedReceivesArray;
/** The number of items in @c shieldedReceivesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger shieldedReceivesArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSData *transparentToAddress;

@property(nonatomic, readwrite) int64_t toAmount;

/** timeout in seconds, it works only when it bigger than 0 */
@property(nonatomic, readwrite) int64_t timeout;

@end

#pragma mark - SpendAuthSigParameters

typedef GPB_ENUM(SpendAuthSigParameters_FieldNumber) {
    SpendAuthSigParameters_FieldNumber_Ask = 1,
    SpendAuthSigParameters_FieldNumber_TxHash = 2,
    SpendAuthSigParameters_FieldNumber_Alpha = 3,
};

GPB_FINAL @interface SpendAuthSigParameters : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ask;

@property(nonatomic, readwrite, copy, null_resettable) NSData *txHash;

@property(nonatomic, readwrite, copy, null_resettable) NSData *alpha;

@end

#pragma mark - NfParameters

typedef GPB_ENUM(NfParameters_FieldNumber) {
    NfParameters_FieldNumber_Note = 1,
    NfParameters_FieldNumber_Voucher = 2,
    NfParameters_FieldNumber_Ak = 3,
    NfParameters_FieldNumber_Nk = 4,
};

GPB_FINAL @interface NfParameters : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Note *note;
/** Test to see if @c note has been set. */
@property(nonatomic, readwrite) BOOL hasNote;

@property(nonatomic, readwrite, strong, null_resettable) IncrementalMerkleVoucher *voucher;
/** Test to see if @c voucher has been set. */
@property(nonatomic, readwrite) BOOL hasVoucher;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ak;

@property(nonatomic, readwrite, copy, null_resettable) NSData *nk;

@end

#pragma mark - ExpandedSpendingKeyMessage

typedef GPB_ENUM(ExpandedSpendingKeyMessage_FieldNumber) {
    ExpandedSpendingKeyMessage_FieldNumber_Ask = 1,
    ExpandedSpendingKeyMessage_FieldNumber_Nsk = 2,
    ExpandedSpendingKeyMessage_FieldNumber_Ovk = 3,
};

GPB_FINAL @interface ExpandedSpendingKeyMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ask;

@property(nonatomic, readwrite, copy, null_resettable) NSData *nsk;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ovk;

@end

#pragma mark - ViewingKeyMessage

typedef GPB_ENUM(ViewingKeyMessage_FieldNumber) {
    ViewingKeyMessage_FieldNumber_Ak = 1,
    ViewingKeyMessage_FieldNumber_Nk = 2,
};

GPB_FINAL @interface ViewingKeyMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ak;

@property(nonatomic, readwrite, copy, null_resettable) NSData *nk;

@end

#pragma mark - IncomingViewingKeyMessage

typedef GPB_ENUM(IncomingViewingKeyMessage_FieldNumber) {
    IncomingViewingKeyMessage_FieldNumber_Ivk = 1,
};

GPB_FINAL @interface IncomingViewingKeyMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ivk;

@end

#pragma mark - DiversifierMessage

typedef GPB_ENUM(DiversifierMessage_FieldNumber) {
    DiversifierMessage_FieldNumber_D = 1,
};

GPB_FINAL @interface DiversifierMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *d;

@end

#pragma mark - IncomingViewingKeyDiversifierMessage

typedef GPB_ENUM(IncomingViewingKeyDiversifierMessage_FieldNumber) {
    IncomingViewingKeyDiversifierMessage_FieldNumber_Ivk = 1,
    IncomingViewingKeyDiversifierMessage_FieldNumber_D = 2,
};

GPB_FINAL @interface IncomingViewingKeyDiversifierMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) IncomingViewingKeyMessage *ivk;
/** Test to see if @c ivk has been set. */
@property(nonatomic, readwrite) BOOL hasIvk;

@property(nonatomic, readwrite, strong, null_resettable) DiversifierMessage *d;
/** Test to see if @c d has been set. */
@property(nonatomic, readwrite) BOOL hasD;

@end

#pragma mark - PaymentAddressMessage

typedef GPB_ENUM(PaymentAddressMessage_FieldNumber) {
    PaymentAddressMessage_FieldNumber_D = 1,
    PaymentAddressMessage_FieldNumber_PkD = 2,
    PaymentAddressMessage_FieldNumber_PaymentAddress = 3,
};

GPB_FINAL @interface PaymentAddressMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) DiversifierMessage *d;
/** Test to see if @c d has been set. */
@property(nonatomic, readwrite) BOOL hasD;

@property(nonatomic, readwrite, copy, null_resettable) NSData *pkD;

@property(nonatomic, readwrite, copy, null_resettable) NSString *paymentAddress;

@end

#pragma mark - ShieldedAddressInfo

typedef GPB_ENUM(ShieldedAddressInfo_FieldNumber) {
    ShieldedAddressInfo_FieldNumber_Sk = 1,
    ShieldedAddressInfo_FieldNumber_Ask = 2,
    ShieldedAddressInfo_FieldNumber_Nsk = 3,
    ShieldedAddressInfo_FieldNumber_Ovk = 4,
    ShieldedAddressInfo_FieldNumber_Ak = 5,
    ShieldedAddressInfo_FieldNumber_Nk = 6,
    ShieldedAddressInfo_FieldNumber_Ivk = 7,
    ShieldedAddressInfo_FieldNumber_D = 8,
    ShieldedAddressInfo_FieldNumber_PkD = 9,
    ShieldedAddressInfo_FieldNumber_PaymentAddress = 10,
};

GPB_FINAL @interface ShieldedAddressInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *sk;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ask;

@property(nonatomic, readwrite, copy, null_resettable) NSData *nsk;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ovk;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ak;

@property(nonatomic, readwrite, copy, null_resettable) NSData *nk;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ivk;

@property(nonatomic, readwrite, copy, null_resettable) NSData *d;

@property(nonatomic, readwrite, copy, null_resettable) NSData *pkD;

@property(nonatomic, readwrite, copy, null_resettable) NSString *paymentAddress;

@end

#pragma mark - NoteParameters

typedef GPB_ENUM(NoteParameters_FieldNumber) {
    NoteParameters_FieldNumber_Ak = 1,
    NoteParameters_FieldNumber_Nk = 2,
    NoteParameters_FieldNumber_Note = 3,
    NoteParameters_FieldNumber_Txid = 4,
    NoteParameters_FieldNumber_Index = 5,
};

GPB_FINAL @interface NoteParameters : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ak;

@property(nonatomic, readwrite, copy, null_resettable) NSData *nk;

@property(nonatomic, readwrite, strong, null_resettable) Note *note;
/** Test to see if @c note has been set. */
@property(nonatomic, readwrite) BOOL hasNote;

@property(nonatomic, readwrite, copy, null_resettable) NSData *txid;

@property(nonatomic, readwrite) int32_t index;

@end

#pragma mark - SpendResult

typedef GPB_ENUM(SpendResult_FieldNumber) {
    SpendResult_FieldNumber_Result = 1,
    SpendResult_FieldNumber_Message = 2,
};

GPB_FINAL @interface SpendResult : GPBMessage

@property(nonatomic, readwrite) BOOL result;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

#pragma mark - TransactionInfoList

typedef GPB_ENUM(TransactionInfoList_FieldNumber) {
    TransactionInfoList_FieldNumber_TransactionInfoArray = 1,
};

GPB_FINAL @interface TransactionInfoList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TransactionInfo*> *transactionInfoArray;
/** The number of items in @c transactionInfoArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger transactionInfoArray_Count;

@end

#pragma mark - SpendNoteTRC20

typedef GPB_ENUM(SpendNoteTRC20_FieldNumber) {
    SpendNoteTRC20_FieldNumber_Note = 1,
    SpendNoteTRC20_FieldNumber_Alpha = 2,
    SpendNoteTRC20_FieldNumber_Root = 3,
    SpendNoteTRC20_FieldNumber_Path = 4,
    SpendNoteTRC20_FieldNumber_Pos = 5,
};

GPB_FINAL @interface SpendNoteTRC20 : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Note *note;
/** Test to see if @c note has been set. */
@property(nonatomic, readwrite) BOOL hasNote;

@property(nonatomic, readwrite, copy, null_resettable) NSData *alpha;

@property(nonatomic, readwrite, copy, null_resettable) NSData *root;

@property(nonatomic, readwrite, copy, null_resettable) NSData *path;

@property(nonatomic, readwrite) int64_t pos;

@end

#pragma mark - PrivateShieldedTRC20Parameters

typedef GPB_ENUM(PrivateShieldedTRC20Parameters_FieldNumber) {
    PrivateShieldedTRC20Parameters_FieldNumber_Ask = 1,
    PrivateShieldedTRC20Parameters_FieldNumber_Nsk = 2,
    PrivateShieldedTRC20Parameters_FieldNumber_Ovk = 3,
    PrivateShieldedTRC20Parameters_FieldNumber_FromAmount = 4,
    PrivateShieldedTRC20Parameters_FieldNumber_ShieldedSpendsArray = 5,
    PrivateShieldedTRC20Parameters_FieldNumber_ShieldedReceivesArray = 6,
    PrivateShieldedTRC20Parameters_FieldNumber_TransparentToAddress = 7,
    PrivateShieldedTRC20Parameters_FieldNumber_ToAmount = 8,
    PrivateShieldedTRC20Parameters_FieldNumber_ShieldedTrc20ContractAddress = 9,
};

GPB_FINAL @interface PrivateShieldedTRC20Parameters : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ask;

@property(nonatomic, readwrite, copy, null_resettable) NSData *nsk;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ovk;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fromAmount;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SpendNoteTRC20*> *shieldedSpendsArray;
/** The number of items in @c shieldedSpendsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger shieldedSpendsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ReceiveNote*> *shieldedReceivesArray;
/** The number of items in @c shieldedReceivesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger shieldedReceivesArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSData *transparentToAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSString *toAmount;

@property(nonatomic, readwrite, copy, null_resettable) NSData *shieldedTrc20ContractAddress;

@end

#pragma mark - PrivateShieldedTRC20ParametersWithoutAsk

typedef GPB_ENUM(PrivateShieldedTRC20ParametersWithoutAsk_FieldNumber) {
    PrivateShieldedTRC20ParametersWithoutAsk_FieldNumber_Ak = 1,
    PrivateShieldedTRC20ParametersWithoutAsk_FieldNumber_Nsk = 2,
    PrivateShieldedTRC20ParametersWithoutAsk_FieldNumber_Ovk = 3,
    PrivateShieldedTRC20ParametersWithoutAsk_FieldNumber_FromAmount = 4,
    PrivateShieldedTRC20ParametersWithoutAsk_FieldNumber_ShieldedSpendsArray = 5,
    PrivateShieldedTRC20ParametersWithoutAsk_FieldNumber_ShieldedReceivesArray = 6,
    PrivateShieldedTRC20ParametersWithoutAsk_FieldNumber_TransparentToAddress = 7,
    PrivateShieldedTRC20ParametersWithoutAsk_FieldNumber_ToAmount = 8,
    PrivateShieldedTRC20ParametersWithoutAsk_FieldNumber_ShieldedTrc20ContractAddress = 9,
};

GPB_FINAL @interface PrivateShieldedTRC20ParametersWithoutAsk : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ak;

@property(nonatomic, readwrite, copy, null_resettable) NSData *nsk;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ovk;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fromAmount;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SpendNoteTRC20*> *shieldedSpendsArray;
/** The number of items in @c shieldedSpendsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger shieldedSpendsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ReceiveNote*> *shieldedReceivesArray;
/** The number of items in @c shieldedReceivesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger shieldedReceivesArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSData *transparentToAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSString *toAmount;

@property(nonatomic, readwrite, copy, null_resettable) NSData *shieldedTrc20ContractAddress;

@end

#pragma mark - ShieldedTRC20Parameters

typedef GPB_ENUM(ShieldedTRC20Parameters_FieldNumber) {
    ShieldedTRC20Parameters_FieldNumber_SpendDescriptionArray = 1,
    ShieldedTRC20Parameters_FieldNumber_ReceiveDescriptionArray = 2,
    ShieldedTRC20Parameters_FieldNumber_BindingSignature = 3,
    ShieldedTRC20Parameters_FieldNumber_MessageHash = 4,
    ShieldedTRC20Parameters_FieldNumber_TriggerContractInput = 5,
    ShieldedTRC20Parameters_FieldNumber_ParameterType = 6,
};

GPB_FINAL @interface ShieldedTRC20Parameters : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SpendDescription*> *spendDescriptionArray;
/** The number of items in @c spendDescriptionArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger spendDescriptionArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ReceiveDescription*> *receiveDescriptionArray;
/** The number of items in @c receiveDescriptionArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger receiveDescriptionArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSData *bindingSignature;

@property(nonatomic, readwrite, copy, null_resettable) NSData *messageHash;

@property(nonatomic, readwrite, copy, null_resettable) NSString *triggerContractInput;

@property(nonatomic, readwrite, copy, null_resettable) NSString *parameterType;

@end

#pragma mark - IvkDecryptTRC20Parameters

typedef GPB_ENUM(IvkDecryptTRC20Parameters_FieldNumber) {
    IvkDecryptTRC20Parameters_FieldNumber_StartBlockIndex = 1,
    IvkDecryptTRC20Parameters_FieldNumber_EndBlockIndex = 2,
    IvkDecryptTRC20Parameters_FieldNumber_ShieldedTrc20ContractAddress = 3,
    IvkDecryptTRC20Parameters_FieldNumber_Ivk = 4,
    IvkDecryptTRC20Parameters_FieldNumber_Ak = 5,
    IvkDecryptTRC20Parameters_FieldNumber_Nk = 6,
    IvkDecryptTRC20Parameters_FieldNumber_EventsArray = 7,
};

GPB_FINAL @interface IvkDecryptTRC20Parameters : GPBMessage

@property(nonatomic, readwrite) int64_t startBlockIndex;

@property(nonatomic, readwrite) int64_t endBlockIndex;

@property(nonatomic, readwrite, copy, null_resettable) NSData *shieldedTrc20ContractAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ivk;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ak;

@property(nonatomic, readwrite, copy, null_resettable) NSData *nk;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *eventsArray;
/** The number of items in @c eventsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger eventsArray_Count;

@end

#pragma mark - OvkDecryptTRC20Parameters

typedef GPB_ENUM(OvkDecryptTRC20Parameters_FieldNumber) {
    OvkDecryptTRC20Parameters_FieldNumber_StartBlockIndex = 1,
    OvkDecryptTRC20Parameters_FieldNumber_EndBlockIndex = 2,
    OvkDecryptTRC20Parameters_FieldNumber_Ovk = 3,
    OvkDecryptTRC20Parameters_FieldNumber_ShieldedTrc20ContractAddress = 4,
    OvkDecryptTRC20Parameters_FieldNumber_EventsArray = 5,
};

GPB_FINAL @interface OvkDecryptTRC20Parameters : GPBMessage

@property(nonatomic, readwrite) int64_t startBlockIndex;

@property(nonatomic, readwrite) int64_t endBlockIndex;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ovk;

@property(nonatomic, readwrite, copy, null_resettable) NSData *shieldedTrc20ContractAddress;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *eventsArray;
/** The number of items in @c eventsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger eventsArray_Count;

@end

#pragma mark - DecryptNotesTRC20

typedef GPB_ENUM(DecryptNotesTRC20_FieldNumber) {
    DecryptNotesTRC20_FieldNumber_NoteTxsArray = 1,
};

GPB_FINAL @interface DecryptNotesTRC20 : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DecryptNotesTRC20_NoteTx*> *noteTxsArray;
/** The number of items in @c noteTxsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger noteTxsArray_Count;

@end

#pragma mark - DecryptNotesTRC20_NoteTx

typedef GPB_ENUM(DecryptNotesTRC20_NoteTx_FieldNumber) {
    DecryptNotesTRC20_NoteTx_FieldNumber_Note = 1,
    DecryptNotesTRC20_NoteTx_FieldNumber_Position = 2,
    DecryptNotesTRC20_NoteTx_FieldNumber_IsSpent = 3,
    DecryptNotesTRC20_NoteTx_FieldNumber_Txid = 4,
    DecryptNotesTRC20_NoteTx_FieldNumber_Index = 5,
    DecryptNotesTRC20_NoteTx_FieldNumber_ToAmount = 6,
    DecryptNotesTRC20_NoteTx_FieldNumber_TransparentToAddress = 7,
};

GPB_FINAL @interface DecryptNotesTRC20_NoteTx : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Note *note;
/** Test to see if @c note has been set. */
@property(nonatomic, readwrite) BOOL hasNote;

@property(nonatomic, readwrite) int64_t position;

@property(nonatomic, readwrite) BOOL isSpent;

@property(nonatomic, readwrite, copy, null_resettable) NSData *txid;

/** the index of note in txid */
@property(nonatomic, readwrite) int32_t index;

@property(nonatomic, readwrite, copy, null_resettable) NSString *toAmount;

@property(nonatomic, readwrite, copy, null_resettable) NSData *transparentToAddress;

@end

#pragma mark - NfTRC20Parameters

typedef GPB_ENUM(NfTRC20Parameters_FieldNumber) {
    NfTRC20Parameters_FieldNumber_Note = 1,
    NfTRC20Parameters_FieldNumber_Ak = 2,
    NfTRC20Parameters_FieldNumber_Nk = 3,
    NfTRC20Parameters_FieldNumber_Position = 4,
    NfTRC20Parameters_FieldNumber_ShieldedTrc20ContractAddress = 5,
};

GPB_FINAL @interface NfTRC20Parameters : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Note *note;
/** Test to see if @c note has been set. */
@property(nonatomic, readwrite) BOOL hasNote;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ak;

@property(nonatomic, readwrite, copy, null_resettable) NSData *nk;

@property(nonatomic, readwrite) int64_t position;

@property(nonatomic, readwrite, copy, null_resettable) NSData *shieldedTrc20ContractAddress;

@end

#pragma mark - NullifierResult

typedef GPB_ENUM(NullifierResult_FieldNumber) {
    NullifierResult_FieldNumber_IsSpent = 1,
};

GPB_FINAL @interface NullifierResult : GPBMessage

@property(nonatomic, readwrite) BOOL isSpent;

@end

#pragma mark - ShieldedTRC20TriggerContractParameters

typedef GPB_ENUM(ShieldedTRC20TriggerContractParameters_FieldNumber) {
    ShieldedTRC20TriggerContractParameters_FieldNumber_ShieldedTrc20Parameters = 1,
    ShieldedTRC20TriggerContractParameters_FieldNumber_SpendAuthoritySignatureArray = 2,
    ShieldedTRC20TriggerContractParameters_FieldNumber_Amount = 3,
    ShieldedTRC20TriggerContractParameters_FieldNumber_TransparentToAddress = 4,
};

GPB_FINAL @interface ShieldedTRC20TriggerContractParameters : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ShieldedTRC20Parameters *shieldedTrc20Parameters;
/** Test to see if @c shieldedTrc20Parameters has been set. */
@property(nonatomic, readwrite) BOOL hasShieldedTrc20Parameters;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BytesMessage*> *spendAuthoritySignatureArray;
/** The number of items in @c spendAuthoritySignatureArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger spendAuthoritySignatureArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *amount;

@property(nonatomic, readwrite, copy, null_resettable) NSData *transparentToAddress;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
