// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/zksnark.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Transaction;
@class TronTransaction;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum ZksnarkResponse_Code

typedef GPB_ENUM(ZksnarkResponse_Code) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ZksnarkResponse_Code_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ZksnarkResponse_Code_Success = 0,
  ZksnarkResponse_Code_Failed = 1,
};

GPBEnumDescriptor *ZksnarkResponse_Code_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ZksnarkResponse_Code_IsValidValue(int32_t value);

#pragma mark - ZksnarkRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ZksnarkRoot : GPBRootObject
@end

#pragma mark - ZksnarkRequest

typedef GPB_ENUM(ZksnarkRequest_FieldNumber) {
  ZksnarkRequest_FieldNumber_Transaction = 1,
  ZksnarkRequest_FieldNumber_Sighash = 2,
  ZksnarkRequest_FieldNumber_ValueBalance = 3,
  ZksnarkRequest_FieldNumber_TxId = 4,
};

@interface ZksnarkRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) TronTransaction *transaction;
/** Test to see if @c transaction has been set. */
@property(nonatomic, readwrite) BOOL hasTransaction;

@property(nonatomic, readwrite, copy, null_resettable) NSData *sighash;

@property(nonatomic, readwrite) int64_t valueBalance;

@property(nonatomic, readwrite, copy, null_resettable) NSString *txId;

@end

#pragma mark - ZksnarkResponse

typedef GPB_ENUM(ZksnarkResponse_FieldNumber) {
  ZksnarkResponse_FieldNumber_Code = 1,
};

@interface ZksnarkResponse : GPBMessage

@property(nonatomic, readwrite) ZksnarkResponse_Code code;

@end

/**
 * Fetches the raw value of a @c ZksnarkResponse's @c code property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ZksnarkResponse_Code_RawValue(ZksnarkResponse *message);
/**
 * Sets the raw value of an @c ZksnarkResponse's @c code property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetZksnarkResponse_Code_RawValue(ZksnarkResponse *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
